mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views

urlpatterns = [
    path('', include('tasks.url2')),
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/tasks/tutorial/list/'), name='logout'),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('api/', views.api_data),
    path('article/list/', views.article_list),
    path('article/<int:pk>/', views.article_one, name='article_one'),
    path('tutorial/list/', views.tutorial_list, name='tutorial_list'),
    path('tutorial/<int:pk>/', views.tutorial_one, name='tutorial_one'),
    path('tutorial/new/', views.tutorial_new, name='tutorial_new'),
]

tasks/models.py
from django.db import models
from tinymce.models import HTMLField


class Article(models.Model):
    title = models.CharField('标题', max_length=100, default='')
    abstract = models.TextField('摘要', null=True, blank=True)
    content = HTMLField('内容', null=True, blank=True)
    source = models.CharField('原文地址', max_length=300, null=True, blank=True)
    codeurl = models.TextField('代码地址', null=True, blank=True)
    image = models.TextField('图片地址', null=True, blank=True)
    keyword = models.CharField('公众号关键词', max_length=20, null=True, blank=True)
    exist = models.BooleanField('是否存在', default=True)
    readcount = models.IntegerField('阅读人数', default=0)
    likecount = models.IntegerField('喜欢人数', default=0)
    commentcount = models.IntegerField('评论人数', default=0)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)

    def __str__(self):
        return '%d，%s' % (self.id, self.title)


class Tutorial(models.Model):
    title = models.CharField('标题', max_length=100, default='')
    index = models.IntegerField('序号', unique=True)
    content = HTMLField('内容')
    readcount = models.IntegerField('阅读人数', default=0)
    likecount = models.IntegerField('喜欢人数', default=0)
    commentcount = models.IntegerField('评论人数', default=0)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    exist = models.BooleanField('是否存在', default=True)

    def __str__(self):
        return '%d，%s' % (self.index, self.title)

    class Meta:
        ordering = ['index']


class HostInfo(models.Model):
    LOCK_STATUS = (
        (0, '未锁定'),
        (1, '锁定')
    )
    host = models.CharField('主机ip', max_length=32, unique=True)
    count = models.IntegerField('请求次数', default=1)
    start_time = models.DateTimeField('请求开始时间', auto_now_add=True)
    last_active_time = models.DateTimeField('最近请求时间', auto_now_add=True)
    is_lock = models.IntegerField('ip状态', choices=LOCK_STATUS, default=0)


class TaskList(models.Model):
    title = models.CharField('标题', max_length=100)
    index = models.IntegerField('序号', unique=True)
    content = HTMLField('内容')
    url = models.CharField('url', max_length=100)
    exist = models.BooleanField('是否存在', default=True)

    class Meta:
        ordering = ['index']

tasks/forms.py
from django import forms

from .models import Tutorial


class PostForm(forms.ModelForm):

    class Meta:
        model = Tutorial
        fields = ('title', 'index', 'content',)

tasks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, Http404
from django.shortcuts import redirect

from .forms import PostForm

from .models import Article, Tutorial, TaskList

import random, datetime

UA_LIST = [
    'Trident',  # IE内核
    'Presto',  # opera内核
    'AppleWebKit',  # 苹果、谷歌内核
    'Gecko',  # 火狐内核
    'Android',  # android终端
    'Adr',  # android终端
    'iPhone',  # 是否为iPhone或者QQHD浏览器
    'iPad',  # 是否iPad
]

ENCODE_LIST = {
    '0': '&#xF369;',
    '1': '&#xF52C;',
    '2': '&#xe072;',
    '3': '&#xF2bd;',
    '4': '&#xF51D;',
    '5': '&#xF7D9;',
    '6': '&#xE52C;',
    '7': '&#xF783;',
    '8': '&#xE8B8;',
    '9': '&#xEB7F;',
}


def index(request):
    tasklist = TaskList.objects.filter(exist=True)
    return render(request, 'tasks/index.html', {'tasklist': tasklist})


def api_data(request):
    articles = Article.objects.filter(exist=True).order_by('create_time')
    data = [{
        'id':art.id,
        'title':art.title,
        'image': art.image,
        'readcount':art.readcount
    } for art in articles]

    return JsonResponse({'articles': data})


def article_list(request):
    articles = Article.objects.filter(exist=True).order_by('create_time')
    return render(request, 'tasks/article_list.html', {'items': articles})


def article_one(request, pk):
    art_one = get_object_or_404(Article, pk=pk, exist=True)
    return render(request, 'tasks/article_one.html', {'item': art_one})


def text_encode(num): # 用于数字图片的加密
    return ''.join(ENCODE_LIST[i] for i in str(num))


def web_encode(num): # 用于前端加密
    today = datetime.date.today()
    day = today.day
    month = today.month

    num_list = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] # list('0123456789')
    random.shuffle(num_list)
    encode_num_list = (num_list.index(i) for i in str(num))

    join_str = str(random.random())
    num_encode = join_str.join(str(day * item + month) for item in encode_num_list)

    return num_encode, join_str, num_list


def judge_ua_host(request): # 判断是否有 UA 或者 host
    meta = request.META
    user_agent = meta.get('HTTP_USER_AGENT')
    host = meta.get('HTTP_HOST')
    real_host = request.build_absolute_uri('/').split('//')[1][:-1]

    # print("request.build_absolute_uri('/')", request.build_absolute_uri('/'))
    # print('request.META: ', meta)
    # print('user_agent: ', user_agent)
    # print('host: ', host)
    # print('real_host: ', real_host)

    if not user_agent or host != real_host: # 如果没有 ua 或者 host 不符
        return HttpResponse('非正常请求', status=403)

    for ua in UA_LIST: # 如果 ua 不符合要求
        if ua in user_agent:
            break
    else:
        return HttpResponse('非正常请求', status=403)


def tutorial_list(request):

    response = judge_ua_host(request)
    if response:
        return response

    tutorials = Tutorial.objects.filter(exist=True)

    return render(request, 'tasks/tutorial_list.html', {'items': tutorials})


def tutorial_one(request, pk):

    response = judge_ua_host(request)

    if response:
        return response

    if not request.user.is_authenticated and pk > 11: # 未登录状态只能查看前几课内容
        return render(request, 'registration/login.html', {})

    tut_one = get_object_or_404(Tutorial, id=pk, exist=True)

    all_tut = Tutorial.objects.filter(exist=True)

    tut_last = all_tut.filter(index__lt=tut_one.index).last()
    tut_next = all_tut.filter(index__gt=tut_one.index).first()

    readcount_encode, join_str, num_list = web_encode(tut_one.readcount)

    # print(readcount_encode, join_str)

    return render(request, 'tasks/article_one.html', {
        'item': tut_one,
        'last': tut_last,
        'next': tut_next,
        'readcount': "%s" % readcount_encode,
        'join_str': join_str,
        'num_list': ''.join(num_list),
        # 'readcount': text_encode(tut_one.readcount),
        'likecount': text_encode(tut_one.likecount),
        'commentcount': text_encode(tut_one.commentcount),
    })


def tutorial_new(request):

    response = judge_ua_host(request)
    if response:
        return response

    if not request.user.is_authenticated:  # 未登录状态需要先登录
        return render(request, 'registration/login.html', {})

    if request.method == "POST":
        print('start post')
        form = PostForm(request.POST)
        # print('form:', form, form.is_valid())
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('tasks:tutorial_one', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'tasks/tutorial_new.html', {'form': form})

tasks/templates/tasks/article_list.html
{% extends 'tasks/base.html' %}
{% block title %}爬虫练习{% endblock %}

{% block content %}
    {% load static %}

    <div class="jumbotron lab-jumbotron" style="background-image: url({% static 'tasks/img/office-581131_1920.jpg' %})">
        <div class="container">
            <div class="lab-title">
                <h1>编程教室精选文章</h1>
                <h2>编程世界的进阶之路</h2>
            </div>
        </div>
    </div>

    <div class="container">
        <h2 class="text-center">文章列表</h2>
        <div class="row">
            <div class="x"></div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row lab-row">
            <hr>
            {% for item in items %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="lab-block">
                    <a class="lab-inner-block" href="{% url 'tasks:article_one' item.id %}">
                        <div class="lab-img">
                            <img src="{{ item.image }}" alt="{{ item.title }}" class="lab-img-width">
                        </div>
                        <h3 class="text-center">{{ item.title }}</h3>
                        <p class="text-center">{{ item.abstract }}</p>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

tasks/templates/tasks/article_one.html
{% extends 'tasks/base.html' %}

{% load static %}

{% block head %}
    <style>
        h2 { text-align: center; }
    </style>

    <script>
        var readcount = '{{ readcount }}';
        var join_str = '{{ join_str }}';
        var num_list = '{{ num_list }}';
    </script>

    <script src="{% static 'tasks/js/tutorial.js' %}"></script>
{% endblock %}

{% block content %}
    {% load static %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2"></div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <br />
                <h2>{{item.title}}</h2>
                <br />
                <h5 style="display: flex; justify-content: space-around;">
                    {% if readcount %}
                    <span>阅读数：<span id="try-it"></span></span>
                    <span class="num">点赞数：{{ likecount|safe }}</span>
                    <span class="num">评论数：{{ commentcount|safe }}</span>
                    {% else %}
                    <span>阅读数：{{item.readcount}}</span>
                    <span>点赞数：{{item.likecount}}</span>
                    <span>评论数：{{item.commentcount}}</span>
                    {% endif %}
                </h5>
                <div class="ppx-main-block">
                    {{ item.content|safe }}
                </div>

                <nav aria-label="...">
                    <ul class="pager">
                        <li class="previous">{% if last %}<a href="../{{last.id}}"><span aria-hidden="true">&larr;</span> {{last.index}}.{{last.title}}</a>{% endif %}</li>
                        <li><a href="../list">返回首页</a></li>
                        <li class="next">{% if next %}<a href="../{{next.id}}">{{next.index}}.{{next.title}} <span aria-hidden="true">&rarr;</span></a>{% endif %}</li>
                        <script>$("#try-it").replaceWith(str_end)</script>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2"></div>
        </div>
    </div>
{% endblock %}

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'tasks/css/lesson.css' %}">

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="{% static 'tasks/css/bootstrap.min.css' %}">

    <!-- 下面三行是前端代码高亮 -->
    <link rel="stylesheet" href="{% static 'tasks/css/default.min.css' %}">
    <script src="{% static 'tasks/js/highlight.min.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <link rel="stylesheet" href="{% static 'tasks/css/svgtextcss/a0f3498f963cb4af89a535c674d63493.css' %}">

    <script src="{% static 'tasks/js/bootstrap.js' %}"></script>
    <script src="{% static 'tasks/js/jquery-3.2.1.js' %}"></script>
    {% block head %}{% endblock %}
</head>

<body>
    <header style="position: relative;min-height: 51px;">
        <nav class="navbar navbar-default navbar-fixed-top lab-navbar" style="margin-bottom: 0">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#ul_tags" >
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="http://crossincode.com" class="navbar-brand lab-text" target="_blank">Crossin的编程教室</a>

                </div>
                <div class="collapse navbar-collapse" id="ul_tags">
                    <ul class="nav navbar-nav">
                        <li><a href="https://python666.cn/cls/lesson/list/">Python 入门</a></li>
                        <li><a href="https://python666.cn/static/djangogirl/djangogirl.html">Django Girl</a></li>
                        <li class="dropdown">
                            <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button">码上行动 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="http://crossincode.com/school/course/1/">python零基础入门</a></li>
                                <li><a href="http://crossincode.com/school/course/2/">爬虫实战</a></li>
                            </ul>
                        </li>
                        <li><a href="https://zhuanlan.zhihu.com/crossin" target="_blank">知乎专栏</a></li>
                        <li><a href="https://lab.crossincode.com/" target="_blank">代码案例</a></li>
                        <li><a href="http://bbs.crossincode.com/forum.php" target="_blank">交流论坛</a></li>
                        <li class="active"><a href="/">爬虫练习</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            {% if user.is_authenticated %}
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="glyphicon glyphicon-user"></i>&nbsp; {{ user.username }}
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'logout' %}">退出账号</a></li>
                                </ul>
                            {% else %}
                                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span>&nbsp; 登录</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer class="lab-footer">
        <div class="container-fluid">
            <div class="row lab-footer-row">

            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <h4>Crossin的编程教室</h4>
                <p>编程世界的新手村。扫描右侧二维码，关注公众号，获取更多学习资源</p>
                <p>苏ICP备15063769号</p>

            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <img src="{% static 'tasks/img/wxqr.jpg' %}" alt="Crossin的编程教室二维码" class="lab-ft-img pull-right">
            </div>
        </div>
        </div>
    </footer>

    <script src="{% static 'tasks/js/bootstrap.js' %}"></script>
</body>
</html>

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% block title %}爬虫练习{% endblock %}

{% block content %}
    {% load static %}

    <div class="container-fluid">
        <div class="row lab-row">
            <br />
            <div class="col-lg-3 col-md-3 col-sm-2"></div>
            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
                <div class="lab-block">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="font-size: 22px; display: flex; justify-content: space-between;">
                            <span>爬虫练习 —— 层层关卡，等你来闯！</span>
                        </div>
                    </div>

                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        {% for task in tasklist %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{task.id}}">
                                <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{task.id}}" aria-expanded="false" aria-controls="collapse{{task.id}}">
                                    {{task.title}}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{task.id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{task.id}}">
                                <div class="panel-body">
                                    <div>{{task.content | safe}}</div>
                                    <br />
                                    <a href="{{task.url}}" class="btn btn-primary active" role="button">点击进入</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-2"></div>
        </div>
    </div>

{% endblock %}

tasks/templates/tasks/tutorial_list.html
{% extends 'tasks/base.html' %}
{% block title %}爬虫练习{% endblock %}

{% block content %}
    {% load static %}

    <div class="container-fluid">
        <div class="row lab-row">
            <br />
            <div class="col-lg-3 col-md-3 col-sm-2"></div>
            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
                <div class="lab-block">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="font-size: 22px; display: flex; justify-content: space-between;">
                            <span>Python 入门指南</span>
                            <a href="{% url 'tasks:tutorial_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span>新增文章</a>
                        </div>
                        <ul class="list-group">
                            {% for item in items %}
                                <li class="list-group-item">
                                    <a href="{% url 'tasks:tutorial_one' item.id %}">
                                        <span class="text-center" style="font-size: 18px;">{{ item.index }}. {{ item.title }}</span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-2"></div>
        </div>
    </div>

{% endblock %}

tasks/templates/tasks/tutorial_new.html
{% extends 'tasks/base.html' %}

{% block content %}
    <div class="col-xs-offset-2 col-sm-offset-4 col-md-offset-4 col-xs-8 col-sm-4 col-md-4">
        <br /><br />
        <h1>新增文章</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-primary">保存</button>
        </form>
    </div>
{% endblock %}